In [1]:
import numpy as np
import pandas as pd
from tp2_aux import *
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

from sklearn.manifold import Isomap

PCA_feature_dir="Features/pca_feat.csv"
TSNE_feature_dir="Features/tsne_feat.csv"
ISOMAP_features_dir="Features/isomap_feat.csv"

In [2]:
data=images_as_matrix()
print(data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
data_df=pd.DataFrame(data)
data_df.iloc[5,:].hist();

# Feature extraction

# PCA

In [4]:
pca = PCA(n_components=6)
pca.fit(data)  #Fitting the data for the PCA

#print(pca.singular_values_)
print(pca.explained_variance_ratio_.sum())


0.5883948410325437


In [5]:
pca_data = pca.transform(data)
np.shape(pca_data)

(563, 6)

### Saving features to a file

In [6]:
df_pca=pd.DataFrame(pca_data)
df_pca.to_csv(PCA_feature_dir,index=False)

# T-SNE

In [7]:
t_SNE = TSNE(n_components=6,method="exact").fit_transform(data)
np.shape(t_SNE)


(563, 6)

### Saving features to a file

In [8]:
df_tsne=pd.DataFrame(t_SNE)   
df_tsne.to_csv(TSNE_feature_dir,index=False)  #With 6 features

# Isomap

In [9]:
embedding = Isomap(n_components=6)
data_isomap = embedding.fit_transform(data)
data_isomap.shape

(563, 6)

In [10]:
df_isomap=pd.DataFrame(data_isomap)   
df_isomap.to_csv(ISOMAP_features_dir,index=False)  #With 6 features

In [11]:
df_pca.columns
df=pd.concat([df_pca,df_tsne,df_isomap],axis=1)
df.columns=np.arange(0,len(df.columns))
df.to_csv("Features/18_feat.csv",index=False)